### ISSUE TITLE
links in udfs_8h.md is broken

### ISSUE THREAD

**Issue by aceforeverd** [4paradigm/openmldb-docs-zh#27]

**Comment by lumianph** [comment]
i didn't find this file, which one?

**Comment by lumianph** [comment]
i didn't find this file, which one?

**Comment by aceforeverd** [comment]
> i didn't find this file, which one?

https://github.com/4paradigm/openmldb-docs-zh/blob/dev/reference/sql/functions_and_operators/Files/udfs_8h.md
the file is generated from code, link prefix need update though

**Comment by lumianph** [comment]
this one is fixed already, right? @jingchen2222

**Comment by jingchen2222** [comment]
> this one is fixed already, right? @jingchen2222

yes
